"""Compile Allium `allium model` JSON to deterministic SMT-LIB (QF_UF) for transition graphs."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any

from crucible.errors import UnsupportedModelError


def _run_allium_model(allium_path: Path) -> dict[str, Any]:
    proc = subprocess.run(
        ["allium", "model", str(allium_path)],
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr or proc.stdout or f"allium model failed ({proc.returncode})")
    return json.loads(proc.stdout)


def compile_model_json_to_smt(model: dict[str, Any]) -> str:
    """Emit deterministic SMT-LIB for every entity that declares transition_graphs."""
    lines: list[str] = [
        "; Generated by packages/crucible — deterministic Allium model -> SMT",
        "(set-logic QF_UF)",
    ]
    entities = model.get("entities") or []
    if not entities:
        lines += ["(check-sat)", "(exit)"]
        return "\n".join(lines) + "\n"

    for ent in entities:
        for tg in ent.get("transition_graphs") or []:
            ename = str(ent["name"])
            field = str(tg["field"])
            states = list(tg.get("states") or [])
            edges = tg.get("edges") or []
            if not states:
                raise UnsupportedModelError(f"{ename}.{field}: no states")
            if not all(x.replace("_", "").isalnum() for x in [ename, field, *states]):
                raise UnsupportedModelError(f"unsupported identifiers in {ename}.{field}")
            sort_name = f"{ename}_{field}_State"
            lines.append(f"(declare-sort {sort_name} 0)")
            for st in states:
                lines.append(f"(declare-const {ename}_{field}_{st} {sort_name})")
            if len(states) >= 2:
                names = " ".join(f"{ename}_{field}_{s}" for s in states)
                lines.append(f"(assert (distinct {names}))")
            lines.append(f"(declare-fun step_{ename}_{field} ({sort_name} {sort_name}) Bool)")
            lines.append(f"(declare-const cur_{ename}_{field} {sort_name})")
            edge_sources = sorted({str(e["from"]) for e in edges})
            init = edge_sources[0] if edge_sources else sorted(states)[0]
            lines.append(f"(assert (= cur_{ename}_{field} {ename}_{field}_{init}))")
            for e in edges:
                a = f"{ename}_{field}_{e['from']}"
                b = f"{ename}_{field}_{e['to']}"
                lines.append(f"(assert (step_{ename}_{field} {a} {b}))")
    lines.append("(check-sat)")
    lines.append("(exit)")
    return "\n".join(lines) + "\n"


def compile_allium_file(path: Path) -> str:
    return compile_model_json_to_smt(_run_allium_model(path))


def compile_fixture_transitions(repo_root: Path) -> str:
    return compile_allium_file(repo_root / "tests" / "fixtures" / "crucible" / "transitions.allium")
